ASE_opt: true
Geometry_opt_type: Auto3D
T_values:
- 1
- 10
- 100
- 1000
addh: false
atom_emb: true
atom_emb_list:
- xtb
- sasa
batch_size: 256
class_weights: false
compute_random_baselines: false
device: cpu
emb_split: null
emb_to_use:
- cb
- sec
epochs: 200
filepath: data/bh_treshold_all_all_processed.npz
frac_tst: 0.2
graph_path: null
iterid: 0
kl_annealing_epochs: 50
load_graphs: true
lr: 0.001
max_num_conformers: 3
mode: trn
model_type: seq_emb
morfeus_init: true
n_folds: 5
n_sampling_test: 1000
n_sampling_val: 50
random_seed: 42
save_embeddings: false
save_graphs: false
shuffle: false
split_indices_path: data/split_indices_bh_all.pkl
ss_decay_epochs: 150
ss_epsilon_end: 0.1
ss_epsilon_start: 1
ss_mode: 'on'
stratification_method: iterative
stratify_top_k: 5
temperature: 1.4967454675234544
treshold: 0.4664004131221544
verbose: true
verbose_sec: false
wandb: false
wandb_save_model: false
weight_bce: 2.807119045492115
weight_decay: 1.0e-06
