program: train_gen_model.py
method: bayes  # Options: bayes, random, grid
metric:
  name: accuracy_final
  goal: maximize

# W&B project configuration
entity: AI_RCP
project: PROJECT_PLACEHOLDER

parameters:
  model_type:
    value: MODEL_TYPE_PLACEHOLDER

  filepath:
    value: FILEPATH_PLACEHOLDER

  config_file:
    value: "configs/gen_config.yaml"

  # Learning parameters
  lr:
    values: [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
  
  weight_decay:
    values: [1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
  
  weight_bce:
    distribution: uniform
    min: 0.5
    max: 5.0
  
  batch_size:
    values: [64, 128, 256]
  
  # Training parameters
  epochs:
    value: 200
  
  treshold:
    distribution: uniform
    min: 0.05
    max: 0.6
  
  # Temperature for sampling during evaluation
  temperature:
    distribution: uniform
    min: 0.5
    max: 2.0

  # Class weights testing both True and False
  class_weights:
    values: [True, False]

  #Kl 
  kl_annealing_epochs:
    values: [50, 100, 150]

  #SS decay epochs
  ss_decay_epochs:
    values: [50, 100, 150]

# Early termination to stop poorly performing runs
early_terminate:
  type: hyperband
  min_iter: 50
  eta: 2
  s: 2

# Maximum number of runs in the sweep
run_cap: 50

command:
  - ${env}
  - python
  - ${program}
  - --config_file
  - configs/gen_config.yaml # 📝 IMPORTANT: Path to your gen_config.yaml
  # W&B agent appends sweep params like --frac_trn=0.7